import {
  abcdef,
  abyss,
  androidstudio,
  andromeda,
  atomone,
  aura,
  basicDark,
  basicLight,
  bbedit,
  bespin,
  consoleDark,
  consoleLight,
  copilot,
  darcula,
  dracula,
  duotoneLight,
  duotoneDark,
  eclipse,
  githubLight,
  githubDark,
  gruvboxDark,
  gruvboxLight,
  kimbie,
  material,
  materialLight,
  materialDark,
  monokai,
  monokaiDimmed,
  noctisLilac,
  nord,
  okaidia,
  quietlight,
  red,
  solarizedLight,
  solarizedDark,
  sublime,
  tokyoNight,
  tokyoNightDay,
  tokyoNightStorm,
  tomorrowNightBlue,
  vscodeLight,
  vscodeDark,
  whiteDark,
  whiteLight,
  xcodeLight,
  xcodeDark,
} from '@uiw/codemirror-themes-all';
import { EditorView } from '@codemirror/view';
import { HighlightStyle, syntaxHighlighting } from '@codemirror/language';
import { tags as t } from '@lezer/highlight';

// ── High Contrast Dark ────────────────────────────────────────────────────────
// Pure black (#000000) bg, white text, blue (#6fc3df) accent borders — VSCode HC
const hcDarkBase = EditorView.theme({
  '&': { backgroundColor: '#000000', color: '#ffffff' },
  '.cm-content': { caretColor: '#ffffff' },
  '.cm-cursor': { borderLeftColor: '#ffffff', borderLeftWidth: '2px' },
  '.cm-selectionBackground, ::selection': { backgroundColor: '#0078d4', color: '#ffffff' },
  '.cm-focused .cm-selectionBackground': { backgroundColor: '#0078d4' },
  '.cm-gutters': { backgroundColor: '#000000 !important', color: '#c5c5c5', borderRight: '1px solid #6fc3df !important' },
  '.cm-activeLineGutter': { backgroundColor: '#1a1a1a' },
  '.cm-activeLine': { backgroundColor: '#1a1a1a' },
  '.cm-matchingBracket': { outline: '1px solid #6fc3df', color: 'inherit' },
  '.cm-panels': { backgroundColor: '#000000', color: '#ffffff' },
  '.cm-panels-top': { borderBottom: '1px solid #6fc3df' },
  '.cm-tooltip': { backgroundColor: '#0c0c0c', border: '1px solid #6fc3df', color: '#ffffff' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': { backgroundColor: '#0078d4', color: '#ffffff' },
}, { dark: true });
const hcDarkHighlight = HighlightStyle.define([
  { tag: t.keyword, color: '#569cd6', fontWeight: 'bold' },
  { tag: t.controlKeyword, color: '#c586c0', fontWeight: 'bold' },
  { tag: t.string, color: '#ce9178' },
  { tag: t.number, color: '#b5cea8' },
  { tag: t.bool, color: '#569cd6' },
  { tag: t.null, color: '#569cd6' },
  { tag: t.comment, color: '#6a9955', fontStyle: 'italic' },
  { tag: t.variableName, color: '#9cdcfe' },
  { tag: t.definition(t.variableName), color: '#4fc1ff' },
  { tag: t.function(t.variableName), color: '#dcdcaa' },
  { tag: t.typeName, color: '#4ec9b0' },
  { tag: t.className, color: '#4ec9b0' },
  { tag: t.propertyName, color: '#9cdcfe' },
  { tag: t.attributeName, color: '#9cdcfe' },
  { tag: t.attributeValue, color: '#ce9178' },
  { tag: t.tagName, color: '#4ec9b0' },
  { tag: t.operator, color: '#d4d4d4' },
  { tag: t.punctuation, color: '#d4d4d4' },
  { tag: t.regexp, color: '#d16969' },
  { tag: t.escape, color: '#d7ba7d' },
]);
export const highContrastDark = [hcDarkBase, syntaxHighlighting(hcDarkHighlight)];

// ── High Contrast Light ───────────────────────────────────────────────────────
// Pure white (#ffffff) bg, black text, blue (#0078d4) accent borders — VSCode HC Light
const hcLightBase = EditorView.theme({
  '&': { backgroundColor: '#ffffff', color: '#000000' },
  '.cm-content': { caretColor: '#000000' },
  '.cm-cursor': { borderLeftColor: '#000000', borderLeftWidth: '2px' },
  '.cm-selectionBackground, ::selection': { backgroundColor: '#0078d4', color: '#ffffff' },
  '.cm-focused .cm-selectionBackground': { backgroundColor: '#0078d4' },
  '.cm-gutters': { backgroundColor: '#ffffff !important', color: '#333333', borderRight: '1px solid #0078d4 !important' },
  '.cm-activeLineGutter': { backgroundColor: '#e8f4fd' },
  '.cm-activeLine': { backgroundColor: '#e8f4fd' },
  '.cm-matchingBracket': { outline: '1px solid #0078d4', color: 'inherit' },
  '.cm-panels': { backgroundColor: '#ffffff', color: '#000000' },
  '.cm-panels-top': { borderBottom: '1px solid #0078d4' },
  '.cm-tooltip': { backgroundColor: '#ffffff', border: '1px solid #0078d4', color: '#000000' },
  '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': { backgroundColor: '#0078d4', color: '#ffffff' },
}, { dark: false });
const hcLightHighlight = HighlightStyle.define([
  { tag: t.keyword, color: '#0000ff', fontWeight: 'bold' },
  { tag: t.controlKeyword, color: '#af00db', fontWeight: 'bold' },
  { tag: t.string, color: '#a31515' },
  { tag: t.number, color: '#098658' },
  { tag: t.bool, color: '#0000ff' },
  { tag: t.null, color: '#0000ff' },
  { tag: t.comment, color: '#008000', fontStyle: 'italic' },
  { tag: t.variableName, color: '#001080' },
  { tag: t.definition(t.variableName), color: '#0070c1' },
  { tag: t.function(t.variableName), color: '#795e26' },
  { tag: t.typeName, color: '#267f99' },
  { tag: t.className, color: '#267f99' },
  { tag: t.propertyName, color: '#001080' },
  { tag: t.attributeName, color: '#e50000' },
  { tag: t.attributeValue, color: '#a31515' },
  { tag: t.tagName, color: '#800000' },
  { tag: t.angleBracket, color: '#800000' },
  { tag: t.operator, color: '#000000' },
  { tag: t.punctuation, color: '#000000' },
  { tag: t.regexp, color: '#811f3f' },
  { tag: t.escape, color: '#ee0000' },
]);
export const highContrastLight = [hcLightBase, syntaxHighlighting(hcLightHighlight)];

export const THEMES = {
  'abcdef': { extension: abcdef, isDark: true, label: 'Abcdef' },
  'abyss': { extension: abyss, isDark: true, label: 'Abyss' },
  'androidstudio': { extension: androidstudio, isDark: true, label: 'Android Studio' },
  'andromeda': { extension: andromeda, isDark: true, label: 'Andromeda' },
  'atomone': { extension: atomone, isDark: true, label: 'Atom One' },
  'aura': { extension: aura, isDark: true, label: 'Aura' },
  'basic-dark': { extension: basicDark, isDark: true, label: 'Basic Dark' },
  'basic-light': { extension: basicLight, isDark: false, label: 'Basic Light' },
  'bbedit': { extension: bbedit, isDark: false, label: 'BBEdit' },
  'bespin': { extension: bespin, isDark: true, label: 'Bespin' },
  'console-dark': { extension: consoleDark, isDark: true, label: 'Console Dark' },
  'console-light': { extension: consoleLight, isDark: false, label: 'Console Light' },
  'copilot': { extension: copilot, isDark: true, label: 'Copilot' },
  'darcula': { extension: darcula, isDark: true, label: 'Darcula' },
  'dracula': { extension: dracula, isDark: true, label: 'Dracula' },
  'duotone-light': { extension: duotoneLight, isDark: false, label: 'Duotone Light' },
  'duotone-dark': { extension: duotoneDark, isDark: true, label: 'Duotone Dark' },
  'eclipse': { extension: eclipse, isDark: false, label: 'Eclipse' },
  'github-light': { extension: githubLight, isDark: false, label: 'GitHub Light' },
  'github-dark': { extension: githubDark, isDark: true, label: 'GitHub Dark' },
  'gruvbox-dark': { extension: gruvboxDark, isDark: true, label: 'Gruvbox Dark' },
  'gruvbox-light': { extension: gruvboxLight, isDark: false, label: 'Gruvbox Light' },
  'hc-dark': { extension: highContrastDark, isDark: true, label: 'High Contrast Dark' },
  'hc-light': { extension: highContrastLight, isDark: false, label: 'High Contrast Light' },
  'kimbie': { extension: kimbie, isDark: true, label: 'Kimbie' },
  'material': { extension: material, isDark: true, label: 'Material' },
  'material-light': { extension: materialLight, isDark: false, label: 'Material Light' },
  'material-dark': { extension: materialDark, isDark: true, label: 'Material Dark' },
  'monokai': { extension: monokai, isDark: true, label: 'Monokai' },
  'monokai-dimmed': { extension: monokaiDimmed, isDark: true, label: 'Monokai Dimmed' },
  'noctis-lilac': { extension: noctisLilac, isDark: false, label: 'Noctis Lilac' },
  'nord': { extension: nord, isDark: true, label: 'Nord' },
  'okaidia': { extension: okaidia, isDark: true, label: 'Okaidia' },
  'quietlight': { extension: quietlight, isDark: false, label: 'Quietlight' },
  'red': { extension: red, isDark: true, label: 'Red' },
  'solarized-light': { extension: solarizedLight, isDark: false, label: 'Solarized Light' },
  'solarized-dark': { extension: solarizedDark, isDark: true, label: 'Solarized Dark' },
  'sublime': { extension: sublime, isDark: true, label: 'Sublime' },
  'tokyo-night': { extension: tokyoNight, isDark: true, label: 'Tokyo Night' },
  'tokyo-night-day': { extension: tokyoNightDay, isDark: false, label: 'Tokyo Night Day' },
  'tokyo-night-storm': { extension: tokyoNightStorm, isDark: true, label: 'Tokyo Night Storm' },
  'tomorrow-night-blue': { extension: tomorrowNightBlue, isDark: true, label: 'Tomorrow Night Blue' },
  'vscode-light': { extension: vscodeLight, isDark: false, label: 'VSCode Light' },
  'vscode-dark': { extension: vscodeDark, isDark: true, label: 'VSCode Dark' },
  'white-dark': { extension: whiteDark, isDark: true, label: 'White Dark' },
  'white-light': { extension: whiteLight, isDark: false, label: 'White Light' },
  'xcode-light': { extension: xcodeLight, isDark: false, label: 'Xcode Light' },
  'xcode-dark': { extension: xcodeDark, isDark: true, label: 'Xcode Dark' },
};

export const DEFAULT_THEME = 'vscode-dark';

export function getThemeExtension(themeId: string, isDark: boolean) {
  if (themeId === 'system') {
    return isDark ? THEMES['vscode-dark'].extension : THEMES['vscode-light'].extension;
  }
  return THEMES[themeId as keyof typeof THEMES]?.extension || THEMES['vscode-dark'].extension;
}
